[package]
name = "todolist-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tera = "1.20.0"
uuid = "1.17.0"
validator = { version = "0.20.0", features = ["derive"]}
